# Generated by Django 4.2.7 on 2026-04-28 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_card', models.FileField(upload_to='documents/')),
                ('pan_card', models.FileField(upload_to='documents/')),
                ('ssc', models.FileField(upload_to='documents/')),
                ('hsc', models.FileField(upload_to='documents/')),
                ('graduation', models.FileField(upload_to='documents/')),
                ('post_graduation', models.FileField(upload_to='documents/')),
                ('photo', models.FileField(upload_to='documents/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate_form')),
            ],
        ),
        migrations.AddField(
            model_name='candidate_form',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.signup'),
        ),
    ]
