# Generated by Django 4.2.7 on 2026-04-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_signup_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_form',
            name='address',
        ),
        migrations.AddField(
            model_name='candidate_form',
            name='experiences',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='candidate_form',
            name='full_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate_form',
            name='passed_out',
            field=models.CharField(default=None, max_length=4),
            preserve_default=False,
        ),
    ]
