# Generated by Django 4.2.7 on 2026-04-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_candidate_form_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_form',
            name='status',
            field=models.CharField(default='form_pending', max_length=30),
        ),
    ]
